<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Calor: We'll be right back!</title>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png">
    <link rel="manifest" href="images/site.webmanifest">
    <link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <style>
        body{background-color:#F3F3F3;color:#000;font-family: 'Raleway', sans-serif;}.container{text-align:center}img{margin:20px auto;width:100%;max-width:320px;height:auto}.panel{background-color:#ffffff;padding:20px 10px;font-size:1.1em;overflow:auto;max-width:600px;border-radius:5px;margin:20px auto}h1{weight:400;}p{weight: 300; line-height:1.6em;margin-bottom:20px}a{color:#fff;font-weight:400}
    </style>
</head>
<body>
<div class="container">
    <div class="panel">
        <img src="images/logo.svg" alt="Calor Logo">
        <p>The site is temporarily down for scheduled maintenance <br/> but we will be back soon.</p>
    </div>
</div>
</body>
</html>
